import { vi } from "vitest";
import type { FinanceiroGateway } from "./financeiro-gateway";

/** Fake completo do FinanceiroGateway pra testes de use case — todo método é `vi.fn()` por
 * padrão, sobrescreva só o que o teste precisa via `overrides`. Centralizado aqui pra não quebrar
 * todo teste existente sempre que o port ganhar um método novo (histórico: já aconteceu 2x). */
export function criarFinanceiroGatewayFake(
  overrides: Partial<FinanceiroGateway> = {},
): FinanceiroGateway {
  return {
    listarClientesOpcoes: vi.fn().mockResolvedValue([]),
    listarCategorias: vi.fn().mockResolvedValue([]),
    criarCategoria: vi.fn(),
    editarCategoria: vi.fn(),
    desativarCategoria: vi.fn(),
    listarContas: vi.fn().mockResolvedValue([]),
    criarConta: vi.fn(),
    editarConta: vi.fn(),
    desativarConta: vi.fn(),
    listarLancamentos: vi.fn().mockResolvedValue([]),
    criarLancamento: vi.fn(),
    editarLancamento: vi.fn(),
    baixarLancamento: vi.fn(),
    estornarBaixaLancamento: vi.fn(),
    obterResumoCaixa: vi.fn(),
    obterFluxoMensal: vi.fn().mockResolvedValue([]),
    obterGastosCategoria: vi.fn().mockResolvedValue([]),
    listarContratos: vi.fn().mockResolvedValue([]),
    criarContrato: vi.fn(),
    editarContrato: vi.fn(),
    gerarRecorrencias: vi.fn().mockResolvedValue(0),
    listarAgingRecebiveis: vi.fn().mockResolvedValue([]),
    importarExtrato: vi.fn().mockResolvedValue({ novas: 0, duplicadas: 0 }),
    listarTransacoesPendentes: vi.fn().mockResolvedValue([]),
    listarRegrasClassificacao: vi.fn().mockResolvedValue([]),
    criarRegraClassificacao: vi.fn(),
    listarLancamentosPrevistosPorConta: vi.fn().mockResolvedValue([]),
    conciliarTransacao: vi.fn(),
    desfazerConciliacao: vi.fn(),
    criarLancamentoDeTransacao: vi.fn(),
    ignorarTransacao: vi.fn(),
    reverterIgnorarTransacao: vi.fn(),
    listarRecorrencias: vi.fn().mockResolvedValue([]),
    criarRecorrencia: vi.fn(),
    editarRecorrencia: vi.fn(),
    desativarRecorrencia: vi.fn(),
    listarAgingPagaveis: vi.fn().mockResolvedValue([]),
    obterProjecaoCaixa: vi.fn().mockResolvedValue([]),
    listarFuncionariosOpcoes: vi.fn().mockResolvedValue([]),
    listarCustosFuncionario: vi.fn().mockResolvedValue([]),
    criarCustoFuncionario: vi.fn(),
    obterRentabilidadeClienteMes: vi.fn().mockResolvedValue([]),
    obterCustoOsPorClienteMes: vi.fn().mockResolvedValue([]),
    anexarComprovante: vi.fn(),
    urlAssinadaComprovante: vi.fn(),
    corrigirLancamento: vi.fn(),
    estornarLancamentoRealizado: vi.fn(),
    criarTransferencia: vi.fn(),
    listarPontosRegua: vi.fn().mockResolvedValue([]),
    criarPontoRegua: vi.fn(),
    editarPontoRegua: vi.fn(),
    desativarPontoRegua: vi.fn(),
    listarEnviosRegua: vi.fn().mockResolvedValue([]),
    emitirCobranca: vi.fn(),
    listarCobrancasPorLancamento: vi.fn().mockResolvedValue([]),
    obterConfigImpostos: vi.fn().mockResolvedValue(null),
    salvarConfigImpostos: vi.fn(),
    provisionarImposto: vi.fn(),
    listarProvisoesImposto: vi.fn().mockResolvedValue([]),
    listarFechamentos: vi.fn().mockResolvedValue([]),
    fecharMes: vi.fn(),
    reabrirMes: vi.fn(),
    obterDreMensal: vi.fn().mockResolvedValue([]),
    obterOrcamentoRealizado: vi.fn().mockResolvedValue([]),
    salvarOrcamentoAnual: vi.fn(),
    ...overrides,
  };
}
